/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * viewKelas.java
 *
 * Created on Mar 23, 2014, 10:41:48 PM
 */
package view;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import kelas.Dosen;
import kelas.KelasKuliah;
import kelas.Ruang;
import kelas.tabelPermintaan;
import kontrol.DosenKontrol;
import kontrol.KelasMatkulKontrol;
import kontrol.PenjadwalanKontrol;
import kontrol.RuangKontrol;
import tabelModel.Dosen_TM;
import tabelModel.KelasMatkulPenjadwalan_TM;
import tabelModel.TabelPermintaan_TM;

/**
 *
 * @author ADHI
 */
public class viewPenjadwalan extends javax.swing.JFrame {

    /**
     * Creates new form viewKelas
     */
    public viewPenjadwalan() {
        initComponents();
        setLocationRelativeTo(null);

        dialog_dosen.setVisible(false);
        dialog_dosen.setSize(777, 480);
        dialog_dosen.setLocationRelativeTo(null);
        dialog_dosen.setTitle("DATA DOSEN");

        dialog_matkul.setVisible(false);
        dialog_matkul.setSize(777, 480);
        dialog_matkul.setLocationRelativeTo(null);
        dialog_matkul.setTitle("DATA MATAKULIAH");

        try {
            updateTabelPermintaan();
            updateTabelDosen();
            isiComboRuang();
        } catch (SQLException ex) {
            Logger.getLogger(viewPenjadwalan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void updateTabelMataKuliah() throws SQLException {
        String kodeDosen = text_dosen.getText().split("-")[0];
        List<KelasKuliah> mktm = KelasMatkulKontrol.getKoneksi().tampilMakulDosen(kodeDosen);//masih kosong
        KelasMatkulPenjadwalan_TM model = new KelasMatkulPenjadwalan_TM(mktm);
        tabel_kelasmatakuliah.setModel(model);
    }

    private void updateTabelDosen() throws SQLException {
        List<Dosen> mktm = DosenKontrol.getKoneksi().tampilDosen();
        Dosen_TM model = new Dosen_TM(mktm);
        Tabel_Dosen.setModel(model);
    }

    private void updateTabelPermintaan() throws SQLException {
        List<tabelPermintaan> mktm = PenjadwalanKontrol.getKoneksi().tampilTabelPermintaan();
        TabelPermintaan_TM model = new TabelPermintaan_TM(mktm);
        Tabel_Permintaan.setModel(model);
    }

    private void isiComboRuang() throws SQLException {
        List<Ruang> ruang = RuangKontrol.getKoneksi().tampilRuangTeori();
        for (Ruang k : ruang) {
            combo_ruang.addItem(k.getIdRuang() + "-" + k.getNamaRuang());
        }
    }
    
    private void kosongkan(){
        text_dosen.setText("");
        text_matkul.setText("");
        text_klsMatkul.setText("");
        labelKelas.setText("");
        combo_hari.setSelectedIndex(0);
        combo_jam.setSelectedIndex(0);
        combo_ruang.setSelectedIndex(0);
        try {
            updateTabelMataKuliah();
        } catch (SQLException ex) {
            Logger.getLogger(viewPenjadwalan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_dosen = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabel_Dosen = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        tomboldialog_dosen = new javax.swing.JButton();
        dialog_matkul = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_kelasmatakuliah = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        text_matkul = new javax.swing.JTextField();
        tomboldialog_matkul = new javax.swing.JButton();
        klikKanan = new javax.swing.JPopupMenu();
        HAPUS = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        matkulButton = new javax.swing.JButton();
        dosenButton = new javax.swing.JButton();
        ruangButton = new javax.swing.JButton();
        kelasButton = new javax.swing.JButton();
        penjadwalanButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tombol_cariMatkul = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        simpanButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        text_dosen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        text_klsMatkul = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tombol_cariDosen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel_Permintaan = new javax.swing.JTable();
        combo_jam = new javax.swing.JComboBox();
        combo_hari = new javax.swing.JComboBox();
        combo_ruang = new javax.swing.JComboBox();
        tombol_tambahPermintaan = new javax.swing.JButton();
        button_batal = new javax.swing.JButton();
        labelKelas = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        dialog_dosen.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(153, 51, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("PENCARIAN DOSEN");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Tabel_Dosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabel_Dosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel_DosenMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabel_Dosen);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("NAMA DOSEN");

        tomboldialog_dosen.setText("BATAL");
        tomboldialog_dosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomboldialog_dosenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 201, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(tomboldialog_dosen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(tomboldialog_dosen)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialog_dosen.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        dialog_matkul.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(153, 51, 0));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel14.setText("PENCARIAN MATAKULIAH");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tabel_kelasmatakuliah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_kelasmatakuliah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_kelasmatakuliahMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabel_kelasmatakuliah);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("MATA KULIAH DOSEN PENGAMPU");

        text_matkul.setEditable(false);

        tomboldialog_matkul.setText("BATAL");
        tomboldialog_matkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomboldialog_matkulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text_matkul, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(tomboldialog_matkul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_matkul, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(tomboldialog_matkul)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialog_matkul.getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        HAPUS.setText("HAPUS");
        HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HAPUSActionPerformed(evt);
            }
        });
        klikKanan.add(HAPUS);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel3.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 80, 40));

        matkulButton.setText("Data Mata Kuliah");
        matkulButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matkulButtonActionPerformed(evt);
            }
        });
        jPanel3.add(matkulButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 120, 40));

        dosenButton.setText("Data Dosen");
        dosenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosenButtonActionPerformed(evt);
            }
        });
        jPanel3.add(dosenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 100, 40));

        ruangButton.setText("Data Ruang");
        ruangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruangButtonActionPerformed(evt);
            }
        });
        jPanel3.add(ruangButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 100, 40));

        kelasButton.setText("Data Kelas");
        kelasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasButtonActionPerformed(evt);
            }
        });
        jPanel3.add(kelasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 100, 40));

        penjadwalanButton.setText("Penjadwalan");
        penjadwalanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjadwalanButtonActionPerformed(evt);
            }
        });
        jPanel3.add(penjadwalanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 110, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 940, 60));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("RUANG");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 50, -1));

        tombol_cariMatkul.setText("Cari");
        tombol_cariMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_cariMatkulActionPerformed(evt);
            }
        });
        jPanel4.add(tombol_cariMatkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabel4.setText("TABEL PERMINTAAN");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        simpanButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        simpanButton1.setText("BUAT JADWAL");
        jPanel4.add(simpanButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 440, 50));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("DOSEN");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        text_dosen.setEditable(false);
        text_dosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_dosenActionPerformed(evt);
            }
        });
        jPanel4.add(text_dosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 320, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("MATKUL");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        text_klsMatkul.setEditable(false);
        text_klsMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_klsMatkulActionPerformed(evt);
            }
        });
        jPanel4.add(text_klsMatkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 240, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("HARI");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 40, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("JAM");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 50, -1));

        tombol_cariDosen.setText("Cari");
        tombol_cariDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_cariDosenActionPerformed(evt);
            }
        });
        jPanel4.add(tombol_cariDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        Tabel_Permintaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabel_Permintaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Tabel_PermintaanMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel_Permintaan);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 870, 120));

        combo_jam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "07:00-09:59", "10:00-12:59", "13:00-15:59", "16:00-18:59" }));
        jPanel4.add(combo_jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 130, -1));

        combo_hari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Senin", "Selasa", "Rabu", "Kamis", "Jumat" }));
        jPanel4.add(combo_hari, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 130, -1));

        combo_ruang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        jPanel4.add(combo_ruang, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 120, -1));

        tombol_tambahPermintaan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tombol_tambahPermintaan.setText("TAMBAH PERMINTAAN");
        tombol_tambahPermintaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_tambahPermintaanActionPerformed(evt);
            }
        });
        jPanel4.add(tombol_tambahPermintaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 240, 90));

        button_batal.setText("BATAL");
        button_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_batalActionPerformed(evt);
            }
        });
        jPanel4.add(button_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        labelKelas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel4.add(labelKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 30, 20));

        jLabel16.setText("KELAS");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 40, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 940, 330));

        jPanel5.setBackground(new java.awt.Color(153, 51, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Wide Latin", 1, 19)); // NOI18N
        jLabel6.setText("Pendidikan Guru Sekolah Dasar");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLabel7.setText("Fakultas Keguruan dan Ilmu Pendidikan - Universitas Sanata Dharma");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel8.setText("Telp (0274) 513301, 515352, Fax. (0274) 562383 ");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo.gif"))); // NOI18N
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 150));

        jLabel10.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel10.setText("Mrican, Tromol Pos 29, Yogyakarta 55002.");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 150));

        jPanel2.setBackground(new java.awt.Color(153, 51, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 940, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        Home asd = new Home();
        asd.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_homeButtonActionPerformed

    private void matkulButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matkulButtonActionPerformed
        viewMataKuliah asd = new viewMataKuliah();
        asd.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_matkulButtonActionPerformed

    private void dosenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosenButtonActionPerformed
        viewDosen asd = new viewDosen();
        asd.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_dosenButtonActionPerformed

    private void ruangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruangButtonActionPerformed
        viewRuang asd = new viewRuang();
        asd.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_ruangButtonActionPerformed

    private void kelasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasButtonActionPerformed
        viewKelas asd = new viewKelas();
        asd.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_kelasButtonActionPerformed

    private void penjadwalanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjadwalanButtonActionPerformed
        viewPenjadwalan asd = new viewPenjadwalan();
        asd.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_penjadwalanButtonActionPerformed

    private void text_dosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_dosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_dosenActionPerformed

    private void text_klsMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_klsMatkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_klsMatkulActionPerformed

    private void tombol_cariDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_cariDosenActionPerformed
        dialog_dosen.setVisible(true);
    }//GEN-LAST:event_tombol_cariDosenActionPerformed

    private void tombol_cariMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_cariMatkulActionPerformed
        dialog_matkul.setVisible(true);
    }//GEN-LAST:event_tombol_cariMatkulActionPerformed

    private void tomboldialog_dosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomboldialog_dosenActionPerformed
        dialog_dosen.setVisible(false);
    }//GEN-LAST:event_tomboldialog_dosenActionPerformed

    private void tomboldialog_matkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomboldialog_matkulActionPerformed
        dialog_matkul.setVisible(false);
    }//GEN-LAST:event_tomboldialog_matkulActionPerformed

    private void Tabel_DosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel_DosenMouseClicked
        int row1 = Tabel_Dosen.getSelectedRow();
        String namaDosen = Tabel_Dosen.getValueAt(row1, 0).toString() + "-" + Tabel_Dosen.getValueAt(row1, 1).toString();
        text_dosen.setText(namaDosen);
        dialog_dosen.setVisible(false);
        text_matkul.setText(namaDosen.split("-")[1]);
        try {
            updateTabelMataKuliah();
        } catch (SQLException ex) {
            Logger.getLogger(viewPenjadwalan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Tabel_DosenMouseClicked

    private void tabel_kelasmatakuliahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_kelasmatakuliahMouseClicked
        int row1 = tabel_kelasmatakuliah.getSelectedRow();
        String namaMatkul = tabel_kelasmatakuliah.getValueAt(row1, 0).toString() + "-"
                + tabel_kelasmatakuliah.getValueAt(row1, 1).toString();
        labelKelas.setText(tabel_kelasmatakuliah.getValueAt(row1, 2).toString());
        text_klsMatkul.setText(namaMatkul);
        dialog_matkul.setVisible(false);
    }//GEN-LAST:event_tabel_kelasmatakuliahMouseClicked

    private void button_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_batalActionPerformed
        kosongkan();
    }//GEN-LAST:event_button_batalActionPerformed

    private void tombol_tambahPermintaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_tambahPermintaanActionPerformed
        try {
            int noRule = PenjadwalanKontrol.getKoneksi().cariNoRule();
            if (noRule == 0) {
                noRule = 1;
            } else {
                noRule++;
            }
            int idKelas = Integer.parseInt(text_klsMatkul.getText().split("-")[0]);
            String ruang;
            if (combo_ruang.getSelectedItem().toString().equals("-")) {
                ruang = combo_ruang.getSelectedItem().toString();
            } else {
                ruang = combo_ruang.getSelectedItem().toString().split("-")[0];
            }
            String hari = combo_hari.getSelectedItem().toString();
            String jam = combo_jam.getSelectedItem().toString();
            boolean cek = PenjadwalanKontrol.getKoneksi().cekRuang(ruang, hari, jam);
            if (cek == true) {
                tabelPermintaan tab = new tabelPermintaan(noRule, idKelas, ruang, hari, jam);
                PenjadwalanKontrol.getKoneksi().insertTabelPermintaan(tab);
                JOptionPane.showMessageDialog(null, "DATA PERMINTAAN" + "\n"
                        + "MATAKULIAH         : " + idKelas + "\n"
                        + "KELAS              : " + labelKelas.getText() + "\n"
                        + "DOSEN PENGAMPU     : " + text_dosen.getText().split("-")[1] + "\n"
                        + "JADWAL PERMINTAAN  : " + "HARI " + hari + " RUANG " + ruang + "\n"
                        + "JAM                : " + jam + "\n"
                        + "BERHASIL DITAMBAHKAN");
                updateTabelPermintaan();
                kosongkan();
            } else {
                JOptionPane.showMessageDialog(null, "RUANG " + ruang + " HARI " + hari + " JAM " + jam + " "
                        + "Telah dipakai oleh matakuliah lain. \n"
                        + "Silahkan pilih Ruang/Hari/Jam lain untuk matakuliah ini.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(viewPenjadwalan.class.getName()).log(Level.SEVERE, null, ex);
        }

//        

    }//GEN-LAST:event_tombol_tambahPermintaanActionPerformed

    private void Tabel_PermintaanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel_PermintaanMouseReleased
        if (evt.isPopupTrigger()) {
            klikKanan.show(this, evt.getX(), evt.getYOnScreen());
        }
    }//GEN-LAST:event_Tabel_PermintaanMouseReleased

    private void HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HAPUSActionPerformed
        int row1 = Tabel_Permintaan.getSelectedRow();
        if (row1 == -1) {
            JOptionPane.showMessageDialog(null, "Silahkan pilih Matakuliah yang hendak di EDIT / HAPUS");
        } else {
            String idKelas = Tabel_Permintaan.getValueAt(row1, 0).toString();
            int data = JOptionPane.showConfirmDialog(null, "Apakah Mau menghapus?", "MENGHAPUS DATA " + idKelas, 1);
            if (data == 0) {
                try {
                    PenjadwalanKontrol.getKoneksi().deleteTabelPermintaan(idKelas);
                    updateTabelPermintaan();
                    JOptionPane.showMessageDialog(null, "Data Permintaan kode " + idKelas + " berhasil dihapus");
                } catch (SQLException ex) {
                    Logger.getLogger(viewPenjadwalan.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
            }
        }
    }//GEN-LAST:event_HAPUSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            java.awt.EventQueue.invokeLater(new Runnable() {

                @Override
                public void run() {
                    new viewPenjadwalan().setVisible(true);
                }
            });
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(viewPenjadwalan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(viewPenjadwalan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(viewPenjadwalan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(viewPenjadwalan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem HAPUS;
    private javax.swing.JTable Tabel_Dosen;
    private javax.swing.JTable Tabel_Permintaan;
    private javax.swing.JButton button_batal;
    private javax.swing.JComboBox combo_hari;
    private javax.swing.JComboBox combo_jam;
    private javax.swing.JComboBox combo_ruang;
    private javax.swing.JDialog dialog_dosen;
    private javax.swing.JDialog dialog_matkul;
    private javax.swing.JButton dosenButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton kelasButton;
    private javax.swing.JPopupMenu klikKanan;
    private javax.swing.JLabel labelKelas;
    private javax.swing.JButton matkulButton;
    private javax.swing.JButton penjadwalanButton;
    private javax.swing.JButton ruangButton;
    private javax.swing.JButton simpanButton1;
    private javax.swing.JTable tabel_kelasmatakuliah;
    private javax.swing.JTextField text_dosen;
    private javax.swing.JTextField text_klsMatkul;
    private javax.swing.JTextField text_matkul;
    private javax.swing.JButton tombol_cariDosen;
    private javax.swing.JButton tombol_cariMatkul;
    private javax.swing.JButton tombol_tambahPermintaan;
    private javax.swing.JButton tomboldialog_dosen;
    private javax.swing.JButton tomboldialog_matkul;
    // End of variables declaration//GEN-END:variables
}
